---

- name: Version Specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}-{{ ansible_lsb.major_release | int}}.yml"
    - "../vars/{{ ansible_os_family }}.yml"


- include: os.yml
- include: join.yml